### ISSUE TITLE
Incomplete notes in GPX file

### ISSUE THREAD

**Issue by franco-bez** [SomeoneElseOSM/Notes01#3]
Hi,

I build my notes.gpx using 

> java -jar Notes01.jar -do_notes -bbox=9.5,46.5,11.5,48.5 -output_gpx=notes.gpx -closed=0 -notes_limit=10000 -notes_symbol='Flag, Red'

I noticed that many of the notes nearby have several comments but only the original note gets displayed on my Garmin Oregon.

Here a few examples:
S N0137713 reads only "baerenseetrails gämgige bezeichnung" on the Oregon

but on OSM  you also find my additional comment
https://www.openstreetmap.org/note/137713#map=17/47.85785/10.66210&layers=N

>     Ich weiß nicht ob das eine gängige Bezeichnung ist.
>     Wenn man da mit dem Mountainbike unterwegs ist trifft es allerdings den "Nagel auf den Kopf"
> 

same problem with notes Nr. 528872 , 524705 and many others

Shouldn't the answering comments also be added to the GPX file ?

Ciao,
  Franco

**Comment by SomeoneElseOSM** [comment]
My recollection is that I didn't do that becaue the eTrex Vista HCx that I have truncates the text field after 30 characters (so for example for http://www.openstreetmap.org/note/87613 I just get "Check road name (all the way t").  Given that it does that, I'd never see comments in the note text on the handheld if the original note text was longer than 30 characters.

Do you know what the maximum length of the Oregon note field is?  Maybe I'll have to upgrade :)

**Comment by franco-bez** [comment]
Hi,
thanks for the fast reply :-)

I don't know the limit, but with some notes I have to scroll at least one page down to read everything.
I suspect at least 512, maybe even more than 1024 for a limit.

here's a screen shot:
http://franco-bez.4lima.de/images/96.png

Ah - by the way - EXECELENT WORK :-)

I really like your tool and use it often. Thanks for sharing it.

Ciao,
  Franco

**Comment by franco-bez** [comment]
Just an idea:

are there any limits for the notes and hints in geocaching ?

As the Oregon is a device that is advertised for it's geocaching capabilities it should at least cover that limit.

**Comment by SomeoneElseOSM** [comment]
I've no idea how the Geocaching stuff works - I've never looked at it.  Maybe it allows more text than 30 (on an eTrex - you obviously don't have a low text limit on an Oregon).  Processing OSM comments as well as the original OSM note text should be pretty straightforward, but no guarantees when I'll get a chance to get around to it :)

**Comment by SomeoneElseOSM** [comment]
... and as an aside (in case anyone else stumbles across this issue) one way of getting longer "waypoints" onto a Garmin device is to convert a file of waypoints into a Garmin ".GPI" file (a proprietary Garmin format, which GPSBabel can handle) and load that.

**Comment by franco-bez** [comment]
I tried to do the programming myself, and I just left you a pull request :-)

**Comment by SomeoneElseOSM** [comment]
Thanks for that!  I'll have a look in a bit...

**Comment by SomeoneElseOSM** [comment]
Merged, thanks!
